# Generated by Django 3.2.16 on 2023-01-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20230106_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='phone',
        ),
    ]
