# Generated by Django 3.2.16 on 2023-01-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20230110_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
